### ISSUE TITLE
Database error when installing and using plugin

### ISSUE THREAD

**Issue by cnoelqb** [internetztube/craft-element-relations#1]
We followed your directions to install the Elements Relations plugins and added the Relations field to our Assets sub-folder. Once I added the field to the subfolder in Assets, I viewed the Assets page and received an error pictured below. I also clicked into one of the Assets and the error appears on that page as well.

Here is where I added the relations field:
![Screen Shot 2021-11-12 at 2 20 00 PM](https://user-images.githubusercontent.com/44276300/141523062-17dc2705-5b65-4d41-b8a2-7fef0adcc297.png)

This is the view when I open the Assets folder:
![Screen Shot 2021-11-12 at 2 31 02 PM](https://user-images.githubusercontent.com/44276300/141524274-137e5822-55a6-43d3-85e0-f5de927d982c.png)

**Comment by internetztube** [comment]
What Version of Craft CMS do you use? @cnoelqb

**Comment by gbowne-quickbase** [comment]
I'm @cnoelqb 's coworker. We're on 3.7.18.2

**Comment by internetztube** [comment]
Thank you for the bug report, the pr, and the proposed solution! I really appreciate it!

```
composer update internetztube/craft-element-relations
```
