### ISSUE TITLE
Support for Craft 4

### ISSUE THREAD

**Issue by internetztube** [internetztube/craft-element-relations#14]

**Comment by fantasticmachine** [comment]
Is there any progress here? Will the plugin be made Craft 4 compatible?

**Comment by turnstylerj** [comment]
Also interested in this.

**Comment by internetztube** [comment]
The first beta is out! Please let me know right away if you encounter any bugs. Thanks!
```
composer require internetztube/craft-element-relations:^2.0.0
```
