### ISSUE TITLE
Bug: Unable to save my profile settings due to undefined $job variable

### ISSUE THREAD

**Issue by peteeveleigh** [internetztube/craft-element-relations#16]
### Steps to reproduce:
Make a change to your own user preferences and click save.

### What I expect:
Preferences should be saved

### What happens:
An exception is thrown

yii\base\ErrorException: Undefined variable $job in /app/vendor/internetztube/craft-element-relations/src/ElementRelations.php:83
Stack trace:
#0 {main}

The issue is that the plugin is trying to push a variable `$job` to the queue, but `$job` hasn't been defined.

### System details
PHP version 8.1 (also present with 7.4.26)
Craft Pro 3.7.39
Element Relations 1.3.5

**Comment by internetztube** [comment]
Thanks for your bug report. Should be fixed with `1.3.6`.
