### ISSUE TITLE
[beta] Unable to create new entries on Craft 4 multi-site

### ISSUE THREAD

**Issue by turnstylerj** [internetztube/craft-element-relations#19]
With Element Relations 2.0.0 beta installed on a Craft 4 multi-site install, I'm unable to create new entries by clicking the "New Entry" button in the main entries view. I'm getting the following in `phperrors.log` when I try:

```
PHP Fatal error:  Type of internetztube\elementRelations\jobs\EventElementAfterSaveJob::$description must be ?string (as in class craft\queue\BaseJob) in /Users/me/Documents/myproject/vendor/internetztube/craft-element-relations/src/jobs/EventElementAfterSaveJob.php on line 10
```

Craft version: 4.0.3
Element Relations 2.0.0-beta.2

**Comment by internetztube** [comment]
Thanks for the bug report! Should be fixed with `2.0.0-beta.3`.
