### ISSUE TITLE
Element Relations task gets stuck in queue until CP page refreshed

### ISSUE THREAD

**Issue by turnstylerj** [internetztube/craft-element-relations#22]
# Description

This is kind of a weird one, and I haven't been able to produce super consistent repro steps, but as I'm working on a site build it seems almost every time I leave the tab I have my CP in, move over to a different browser tab, and come back to the CP later, there's an Element Relations task stuck in the queue until I either reload the page or click on the item going directly to the queue, then it quickly runs and goes away.

![Screen Shot 2022-06-30 at 3 01 40 PM](https://user-images.githubusercontent.com/42223501/176786627-5fbc95b7-d470-46a9-a312-36eac7804780.png)

I would be tempted to think this is a strange Craft bug, but it doesn't happen with any other plugins/tasks I've noticed. And more often than not, whenever I log into the CP of a site with this plugin installed, Element Relations tasks are running and quickly resolve once I load the CP. Like they are for some reason unable to run properly in the background/without a control panel load to trigger them to complete.

Does this make any sense? It's kind of a tricky one to describe/narrow down, but only seems to happen with this plugin.

## Additional Information
Craft CMS: v4.1.0.2
Element Relations: v2.0.0

**Comment by internetztube** [comment]
I'll take a look at it the next days. Thanks for reporting.

**Comment by internetztube** [comment]
I guess this is resolved by https://github.com/craftcms/cms/issues/11832.

**Comment by TheFunkyMonk** [comment]
For what it's worth, this is a different issue. Element Relations is the only plugin that has tasks hanging around like this in the sidebar regardless of whether the queue is running standard or automatically.

**Comment by turnstylerj** [comment]
For what it's worth, this is a different issue. Element Relations is the only plugin that has tasks hanging around like this in the sidebar regardless of whether the queue is running standard or automatically.
