### ISSUE TITLE
FR: Plugin does not track relations in draft

### ISSUE THREAD

**Issue by lukasNo1** [internetztube/craft-element-relations#23]
Hey, the plugin seems to ignore elements that are linked within drafts.

We are using this plugin so we can see if an asset is linked in any entry before we delete it.

Now if an asset is linked in an unpublished draft, it still shows the asset is "unused", which is problematic because it is in fact used and should not be deleted.

Do you think you can change this, so relations in drafts get checked as well?

Craft 3.7.46
craft-element-relations: 1.3.7

**Comment by internetztube** [comment]
This is fixed with the latest release.
