### ISSUE TITLE
Allow illuminate/collections ^9.0 support

### ISSUE THREAD

**Issue by adrienne** [internetztube/craft-element-relations#24]
Currently the plugin can't be installed on PHP 8 because of the composer requirement for illuminate/collections -- adding ^9.0 as a possibility will fix the problem.

**Comment by internetztube** [comment]
Which version are you using? In 2.0.0, `illuminate/collections` is no longer a dependency. 
https://github.com/internetztube/craft-element-relations/blob/2.x/composer.json#L24-L26

**Comment by internetztube** [comment]
I assume you're using `1.x`. In [`1.3.8`](https://github.com/internetztube/craft-element-relations/compare/1.3.7...1.3.8) `illuminate/collections ^9.0` is now alloed as dependency.

**Comment by adrienne** [comment]
@internetztube yeah, sorry, 1.x version because we're still on Craft 3.
