### ISSUE TITLE
Error `undefined index siteId` when refreshing data

### ISSUE THREAD

**Issue by gbowne-quickbase** [internetztube/craft-element-relations#27]
Several developers on my team are getting `undefined index siteId` errors when they add an ElementRelations field to a new entrytype, or try to refresh the data at all
<img width="984" alt="image" src="https://user-images.githubusercontent.com/39066452/186986928-76ab83b4-c2f5-4f7e-89dc-efbb26f9e244.png">

**Comment by internetztube** [comment]
Thanks for the bug report, Greg!

I solved the problem a bit differently. By deleting the first site, it is possible that there is no site with id:1. I used the primary site url as a fallback. Thanks for the pull request, nevertheless. Helped a lot.

**Comment by gbowne-quickbase** [comment]
Thanks so much for the quick turn-around

**Comment by internetztube** [comment]
Now also available in `1.3.9`. @gbowne-quickbase
