### ISSUE TITLE
Related items from within LinkIt and Super Table fields not displaying in Element Relations fields

### ISSUE THREAD

**Issue by stevehurst** [internetztube/craft-element-relations#34]
We have many element relation fields within Super Tables. Both Entries field types and LinkIt fields. Is this supported? We're not seeing them reported in the Element Relations fields we have enabled for different sections.

**Comment by stevehurst** [comment]
Actually, it looks like Entries fields within Super Table fields work as expected, to related entries and assets, but Linkit fields with Entry selected aren't displaying within Element Relations fields.

<img width="1032" alt="Screenshot 2024-05-07 at 2 57 24 PM" src="https://github.com/internetztube/craft-element-relations/assets/20077/2cdcf80e-e446-483f-99c0-d57e7a33c8c1">

**Comment by internetztube** [comment]
This should be fixed with the latest release. Thank you!
