### ISSUE TITLE
Question: is this leftJoin needed?

### ISSUE THREAD

**Issue by webrgp** [internetztube/craft-element-relations#37]
https://github.com/internetztube/craft-element-relations/blob/530bc97be99840dfdc7528fe28b2e78d571a7700/src/services/RelationsService.php#L31

I am working with a really large dataset, and when I count the number of relations from particular entry I get:

- With that left join: it times out
- Without that left join: 1514

I haven't dug too much into it, but [this bit](https://github.com/internetztube/craft-element-relations/blob/530bc97be99840dfdc7528fe28b2e78d571a7700/src/services/RelationsService.php#L40-L56) generates huge queries.

**Comment by internetztube** [comment]
You're totally right! That left join in unnecessary. Thanks for reporting! Just released 3.0.6.

**Comment by webrgp** [comment]
I've created a [PR](https://github.com/internetztube/craft-element-relations/pull/38) to add some table indexes to improve performance.
