### ISSUE TITLE
Bug: Create Refresh Element Relations Cache Jobs fails

### ISSUE THREAD

**Issue by KatieMFritz** [internetztube/craft-element-relations#9]
## Steps to reproduce:

1. Go to Utilities > Element Relations
2. Click `Push Cache Refresh Job Into Queue` button

## What I expect:

The cache should rebuild in the background using the queue.

## What happens:

Failed queue job with the following error message

> Error | Argument 1 passed to internetztube\elementRelations\jobs\CreateRefreshElementRelationsJobsJob::internetztube\elementRelations\jobs\{closure}() must be an instance of Tightenco\Collect\Support\Collection, instance of Illuminate\Support\Collection given, called in /home/forge/[projectname]/vendor/illuminate/collections/Traits/EnumeratesValues.php on line 242

## System details

PHP version  7.4.26
Linux 5.4.0-88-generic
MySQL 5.5.5
Craft Pro 3.7.27.2
Element Relations 1.2.6

## Other notes
> Currently 21.77% of all elements, which have an Elements Relations-Field in their field layout, are cached.
In absolute terms this means 539 out of 2476 elements are cached.

**Comment by internetztube** [comment]
Thanks for the bug report!. It should be fixed with 1.3.0. @KatieMFritz 
```
composer update internetztube/craft-element-relations
```
